// Generated by hazo_auth - do not edit manually
// Route: /api/hazo_auth/user_management/users/roles
// Methods: GET, POST, PUT
export { userManagementUsersRolesGET as GET } from "hazo_auth/server/routes";
export { userManagementUsersRolesPOST as POST } from "hazo_auth/server/routes";
export { userManagementUsersRolesPUT as PUT } from "hazo_auth/server/routes";
