// Generated by hazo_auth - do not edit manually
// Route: /api/auth/[...nextauth]
// Methods: GET, POST
export { nextauthGET as GET } from "hazo_auth/server/routes";
export { nextauthPOST as POST } from "hazo_auth/server/routes";
