// Generated by hazo_auth - do not edit manually
// Route: /api/auth/[...nextauth]
// Methods: GET, POST
import { nextauthGET, nextauthPOST } from "hazo_auth/server/routes";
import { NextRequest } from "next/server";

function debugRequest(req: NextRequest, method: string) {
  const url = new URL(req.url);
  console.log(`\n[DEBUG NextAuth ${method}] ===========================`);
  console.log(`[DEBUG] req.url: ${req.url}`);
  console.log(`[DEBUG] url.origin: ${url.origin}`);
  console.log(`[DEBUG] url.pathname: ${url.pathname}`);
  console.log(`[DEBUG] Host header: ${req.headers.get("host")}`);
  console.log(`[DEBUG] X-Forwarded-Host: ${req.headers.get("x-forwarded-host")}`);
  console.log(`[DEBUG] X-Forwarded-Proto: ${req.headers.get("x-forwarded-proto")}`);
  console.log(`[DEBUG] X-Forwarded-For: ${req.headers.get("x-forwarded-for")}`);
  console.log(`[DEBUG] NEXTAUTH_URL: ${process.env.NEXTAUTH_URL}`);
  console.log(`[DEBUG] AUTH_TRUST_HOST: ${process.env.AUTH_TRUST_HOST}`);
  console.log(`[DEBUG] ============================================\n`);
}

export async function GET(req: NextRequest, context: any) {
  debugRequest(req, "GET");
  return nextauthGET(req, context);
}

export async function POST(req: NextRequest, context: any) {
  debugRequest(req, "POST");
  return nextauthPOST(req, context);
}
