// Generated by hazo_auth - do not edit manually
// Route: /api/hazo_auth/user_management/roles
// Methods: GET, POST, PUT
export { userManagementRolesGET as GET } from "hazo_auth/server/routes";
export { userManagementRolesPOST as POST } from "hazo_auth/server/routes";
export { userManagementRolesPUT as PUT } from "hazo_auth/server/routes";
