// Generated by hazo_auth - do not edit manually
// Route: /api/hazo_auth/user_management/permissions
// Methods: GET, POST, PUT, DELETE
export { userManagementPermissionsGET as GET } from "hazo_auth/server/routes";
export { userManagementPermissionsPOST as POST } from "hazo_auth/server/routes";
export { userManagementPermissionsPUT as PUT } from "hazo_auth/server/routes";
export { userManagementPermissionsDELETE as DELETE } from "hazo_auth/server/routes";
