// Generated by hazo_auth - modified for Next.js 15 compatibility
import { MySettingsPage } from "hazo_auth/pages";
import { PrivacyToggle } from "@/components/privacy-toggle";

export default function Page() {
  return (
    <>
      <MySettingsPage />
      <PrivacyToggle />
    </>
  );
}
