// Generated by hazo_auth - do not edit manually
// Route: /api/hazo_auth/oauth/google/callback
// Methods: GET
import { oauthGoogleCallbackGET } from "hazo_auth/server/routes";
import { NextRequest } from "next/server";

export async function GET(req: NextRequest, context: any) {
  const url = new URL(req.url);
  console.log(`\n[DEBUG OAuth Callback] ===========================`);
  console.log(`[DEBUG] req.url: ${req.url}`);
  console.log(`[DEBUG] url.origin: ${url.origin}`);
  console.log(`[DEBUG] Host header: ${req.headers.get("host")}`);
  console.log(`[DEBUG] X-Forwarded-Host: ${req.headers.get("x-forwarded-host")}`);
  console.log(`[DEBUG] X-Forwarded-Proto: ${req.headers.get("x-forwarded-proto")}`);
  console.log(`[DEBUG] NEXTAUTH_URL: ${process.env.NEXTAUTH_URL}`);
  console.log(`[DEBUG] ============================================\n`);

  const response = await oauthGoogleCallbackGET(req, context);

  console.log(`\n[DEBUG OAuth Callback Response] ==================`);
  console.log(`[DEBUG] Status: ${response.status}`);
  console.log(`[DEBUG] Location header: ${response.headers.get("location")}`);
  console.log(`[DEBUG] ============================================\n`);

  return response;
}
