// Generated by hazo_auth - modified for Next.js 15 compatibility
import { VerifyEmailPage } from "hazo_auth/pages";
import { SignUpEvent } from "./sign-up-event";

export default function Page() {
  return (
    <>
      <SignUpEvent />
      <VerifyEmailPage />
    </>
  );
}
