// Generated by hazo_auth - do not edit manually
// Route: /api/hazo_auth/user_management/users
// Methods: GET, PATCH, POST
export { userManagementUsersGET as GET } from "hazo_auth/server/routes";
export { userManagementUsersPATCH as PATCH } from "hazo_auth/server/routes";
export { userManagementUsersPOST as POST } from "hazo_auth/server/routes";
